amazon-braket/amazon-braket-default-simulator-python

- setup.py
> infra: Use pypi dependency name

- src/braket/default_simulator/_version.py
The only way to update a description in PyPi is to upload new files;
however, uploading an existing version is prohibited. The recommended
way to deal with this is with
[post-releases](https://www.python.org/dev/peps/pep-0440/#post-releases).
> fix: Post-release 1.0.0.post1

- README.md
> documentation: add readthedocs link

- README.md
- tox.ini
> infra: Change tox basepython to python3

- CODEOWNERS
> infra: Add team to CODEOWNERS

- .github/workflows/dependent-tests.yml
> infra: Run unit tests for dependent packages

- .github/workflows/python-package.yml
- src/braket/default_simulator/gate_operations.py
- src/braket/default_simulator/result_types.py
- src/braket/default_simulator/simulator.py
- test/performance/test_performance.py
- test/unit_tests/braket/default_simulator/test_gate_operations.py
- test/unit_tests/braket/default_simulator/test_result_types.py
- test/unit_tests/braket/default_simulator/test_simulator.py
- tox.ini
> infra: Use GitHub source for tox tests

- README.md
- setup.py
- src/braket/default_simulator/__init__.py
- src/braket/default_simulator/state_vector_simulator.py
- test/performance/test_performance.py
- test/unit_tests/braket/default_simulator/test_state_vector_simulator.py
Also renamed DefaultSimulator to StateVectorSimulator to align with other classes.
#69 
> fix: Fix perf tests

- src/braket/default_simulator/density_matrix_simulation.py
- src/braket/default_simulator/gate_operations.py
- src/braket/default_simulator/observables.py
- src/braket/default_simulator/operation.py
- src/braket/default_simulator/operation_helpers.py
- src/braket/default_simulator/result_types.py
- src/braket/default_simulator/simulation.py
- src/braket/default_simulator/simulator.py
- src/braket/default_simulator/state_vector_simulation.py
> documentation: Doc corrections

- src/braket/default_simulator/gate_operations.py
- src/braket/default_simulator/state_vector_simulator.py
- test/unit_tests/braket/default_simulator/test_gate_operations.py
- test/unit_tests/braket/default_simulator/test_state_vector_simulator.py
- tox.ini
This makes certain circuits, such as CHSH, more manageable.
*Issue #, if available:* - https://github.com/aws/amazon-braket-sdk-python/pull/297
This edit to the `default-simulator` repo based on changes proposed in PR #297 on the sdk repo https://github.com/aws/amazon-braket-sdk-python/pull/297
These changes allow the test code (in the PR link above) to run whilst using the control-v gate we have implemented.
Added unit test. More information available at: https://github.com/aws/amazon-braket-sdk-python/pull/297
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before …
> feature: added controlled-sqrt-not gate.

- src/braket/default_simulator/density_matrix_simulator.py
- src/braket/default_simulator/gate_operations.py
- src/braket/default_simulator/state_vector_simulator.py
- test/unit_tests/braket/default_simulator/test_density_matrix_simulator.py
- test/unit_tests/braket/default_simulator/test_gate_operations.py
- test/unit_tests/braket/default_simulator/test_state_vector_simulator.py
Cherry picked commit to main: feature: add ECR gate
> feature: add ECR gate (#5)

- setup.py
- src/braket/default_simulator/openqasm/circuit.py
- src/braket/default_simulator/openqasm/program_context.py
- src/braket/default_simulator/openqasm_density_matrix_simulator.py
- test/unit_tests/braket/default_simulator/openqasm/test_interpreter.py
- test/unit_tests/braket/default_simulator/test_openqasm_density_matrix_simulator.py
Add density matrix simulator for OpenQASM local sim
Tox and manual testing
> feature: braket_oq3_dm simulator

- rebuild_parsers.sh
> fix: antlr version in rebuild parsers script

- .github/workflows/python-package.yml
- src/braket/default_simulator/openqasm/_helpers/casting.py
- src/braket/default_simulator/openqasm/interpreter.py
- test/unit_tests/braket/default_simulator/openqasm/test_interpreter.py
> fix: reenable windows testing

- src/braket/default_simulator/openqasm/_helpers/casting.py
- test/unit_tests/braket/default_simulator/openqasm/test_interpreter.py
Ability to specify floats without a specific register size. Default Python float precision
tox
> feature: unsized floats

- src/braket/default_simulator/openqasm/_helpers/casting.py
- test/unit_tests/braket/default_simulator/openqasm/test_interpreter.py
Support bit strings for input by implementing wrap_value_into_literal
tox
> fix: support bit strings for input

- src/braket/default_simulator/openqasm/interpreter.py
- test/unit_tests/braket/default_simulator/openqasm/test_interpreter.py
Silently support measurement statements
tox
> fix: do not visit identifier for measurement statement

- src/braket/default_simulator/openqasm/interpreter.py
- test/unit_tests/braket/default_simulator/openqasm/test_interpreter.py
> reword advanced language features warning

- src/braket/default_simulator/density_matrix_simulator.py
- src/braket/default_simulator/state_vector_simulator.py
- test/unit_tests/braket/default_simulator/test_density_matrix_simulator.py
- test/unit_tests/braket/default_simulator/test_state_vector_simulator.py
requires all qubit measurements flag -> true
tox
> fix: requires all qubits measurement flag

- src/braket/default_simulator/openqasm/interpreter.py
- test/unit_tests/braket/default_simulator/openqasm/test_interpreter.py
Change warning to not be redundant
tox
> modify warning message

- .github/workflows/dependent-tests.yml
- setup.py
- src/braket/default_simulator/linalg_utils.py
- tox.ini
Point to new release of schemas
tox, manual sanity check
> point to schema release

- conftest.py
- test/unit_tests/braket/default_simulator/conftest.py
add pytester reference in unit test conftest
can only test with release
> fix: modify pytester reference to _pytest.pytester

- conftest.py
- setup.py
bump pytest version to see if it works
tox
> fix: bump pytest version further

- setup.py
This exact commit just pins antlr to 4.8 for compatibility with the Strawberry Fields plugin. However, this commit also completes the launch of OpenQASM support started in #100.
tox
> feature: Simulation of OpenQASM programs

- rebuild_parsers.sh
- src/braket/default_simulator/openqasm/parser/generated/BraketPragmasLexer.py
- src/braket/default_simulator/openqasm/parser/generated/BraketPragmasParser.py
- src/braket/default_simulator/openqasm/parser/generated/BraketPragmasParserVisitor.py
- src/braket/default_simulator/openqasm/parser/generated/qasm3Lexer.py
- src/braket/default_simulator/openqasm/parser/generated/qasm3Parser.py
- src/braket/default_simulator/openqasm/parser/generated/qasm3ParserVisitor.py
rebuild antlr parsers with 4.8
unit and manual verification of no warning
> fix: rebuild parsers with new antlr version

- .gitignore
- src/braket/default_simulator/openqasm/circuit.py
- test/unit_tests/braket/default_simulator/test_state_vector_simulator.py
Handle result types all target correctly
unit test, bdk integ tests
> fix: correct behavior for result types all

- .github/workflows/dependent-tests.yml
> infra: Add SF plugin to dependent tests

- .github/workflows/dependent-tests.yml
- .github/workflows/python-package.yml
> infra: Don't run tests on push to feature branches

- src/braket/default_simulator/openqasm/interpreter.py
- src/braket/default_simulator/openqasm/program_context.py
- test/unit_tests/braket/default_simulator/openqasm/test_interpreter.py
Resolve naming collisions with default gates
unit tests
> feature: allow users to overwrite built-in gates

- src/braket/default_simulator/gate_operations.py
- test/unit_tests/braket/default_simulator/openqasm/test_braket_gates.py
Add IonQ native gates
Unit testing
> feature: add IonQ native gates

- src/braket/analog_hamiltonian_simulator/rydberg/constants.py
- src/braket/analog_hamiltonian_simulator/rydberg/numpy_solver.py
- src/braket/analog_hamiltonian_simulator/rydberg/rydberg_simulator.py
- src/braket/analog_hamiltonian_simulator/rydberg/rydberg_simulator_helpers.py
- src/braket/analog_hamiltonian_simulator/rydberg/rydberg_simulator_result_converter.py
- src/braket/analog_hamiltonian_simulator/rydberg/rydberg_simulator_unit_converter.py
- src/braket/analog_hamiltonian_simulator/rydberg/scipy_solver.py
- src/braket/analog_hamiltonian_simulator/rydberg/validators/atom_arrangement.py
- src/braket/analog_hamiltonian_simulator/rydberg/validators/blockade_radius.py
- src/braket/analog_hamiltonian_simulator/rydberg/validators/field_validator_util.py
- src/braket/analog_hamiltonian_simulator/rydberg/validators/ir_validator.py
- src/braket/analog_hamiltonian_simulator/rydberg/validators/rydberg_coefficient.py
- src/braket/analog_hamiltonian_simulator/rydberg/validators/times_series.py
- test/unit_tests/braket/analog_hamiltonian_simulator/test_convert_unit.py
- test/unit_tests/braket/analog_hamiltonian_simulator/test_get_coefs.py
- test/unit_tests/braket/analog_hamiltonian_simulator/test_get_sparse_ops.py
- test/unit_tests/braket/analog_hamiltonian_simulator/test_validator/validators/test_time_series.py
The flake8 will give errors for style issues
Fix the style issues to pass the flake8 tests
> [WIP] feature/neutral atom simulator fix linters

- setup.cfg
- src/braket/default_simulator/density_matrix_simulator.py
- src/braket/default_simulator/openqasm/interpreter.py
- src/braket/default_simulator/state_vector_simulator.py
- test/unit_tests/braket/default_simulator/openqasm/test_interpreter.py
- test/unit_tests/braket/default_simulator/test_density_matrix_simulator.py
- test/unit_tests/braket/default_simulator/test_state_vector_simulator.py
Update local simulator to forbid adjoint gradient pragma and not raise advanced feature warning for inputs
unit and manual tests
> feature: Adjoint Gradient changes

- test/unit_tests/braket/default_simulator/test_operation_helpers.py
fix numpy ragged array error
unit testing
> fix: numpy ragged array error

- test/unit_tests/braket/default_simulator/test_state_vector_simulator.py
realized test wasn't precisely testing what it was supposed to.
tox
> test: tweak noise on sv test

- .github/workflows/dependent-tests.yml
- .github/workflows/python-package.yml
- src/braket/analog_hamiltonian_simulator/rydberg/numpy_solver.py
- src/braket/analog_hamiltonian_simulator/rydberg/scipy_solver.py
- src/braket/analog_hamiltonian_simulator/rydberg/validators/capabilities_constants.py
- src/braket/analog_hamiltonian_simulator/rydberg/validators/physical_field.py
- src/braket/default_simulator/noise_operations.py
- test/unit_tests/braket/analog_hamiltonian_simulator/test_validator/validators/test_program.py
> update: adding build for python 3.10

- .github/workflows/dependent-tests.yml
- .github/workflows/publish-to-pypi.yml
- .github/workflows/python-package.yml
- README.md
https://github.com/badges/shields/issues/8671
https://github.com/aws-samples/amazon-braket-algorithm-library/commit/40bf548380c56ce4fa95f88e5071ca532a677701
> infra: update github workflows for node12 retirement

- README.md
Removing for consistency with other repositories, where the change was made because the badge offers no useful information.
> doc: Remove Black badge

- src/braket/analog_hamiltonian_simulator/rydberg/rydberg_simulator.py
fix: update default step value in doc string for the rydberg simulator
> fix: update default step value in doc string for the rydberg simulator

- setup.cfg
- setup.py
- tox.ini
> test: parallelize test execution for pytest

- src/braket/analog_hamiltonian_simulator/rydberg/rydberg_simulator_helpers.py
- src/braket/analog_hamiltonian_simulator/rydberg/scipy_solver.py
N/A this PR attempt to improve the performance of `braket_ahs` local simulator. 
For Analog solvers, it is generally more efficient to apply the operators to the state vector and sum the vectors instead of the current implementation, which sums up the operators and then applies that matrix to the state. 
I am unsure if there are any benchmarks for `braket_ahs` local simulator but It is hard to tell based on what I saw in the benchmarks. If need be I can try to implement a simple benchmark to demonstrate that this will be an improvement. 
* Unit tests pass
* Performance analysis shows a regression. However, I am unsure if my changes affect the benchmarks.  
_Put an `x` in the boxes that apply. You can also fill these out …
> Modification to `scipy_integrate_ode_run` In braket_ahs local simulator

- setup.py
- src/braket/default_simulator/density_matrix_simulator.py
- src/braket/default_simulator/state_vector_simulator.py
- test/unit_tests/braket/default_simulator/test_density_matrix_simulator.py
- test/unit_tests/braket/default_simulator/test_state_vector_simulator.py
Add supported modifiers to properties
unit tests updated and manually inspected properties
> feat: update local sim properties to include supported modifiers

- .github/workflows/python-package.yml
- setup.py
feat: add support for python 3.11
> feat: add support for python 3.11

- src/braket/default_simulator/noise_operations.py
- src/braket/default_simulator/openqasm/parser/braket_pragmas.py
- src/braket/default_simulator/openqasm/program_context.py
Remove AbstractBraketPragmaNodeVisitor and Add properties: probability, gamma
> feat: Fix program context

- src/braket/default_simulator/openqasm/program_context.py
- test/unit_tests/braket/default_simulator/openqasm/test_program_context.py
> feat: Allow prebuilt circuits in `ProgramContext`

- src/braket/default_simulator/openqasm/interpreter.py
- src/braket/default_simulator/openqasm/program_context.py
- test/unit_tests/braket/default_simulator/openqasm/test_interpreter.py
physical qubits
todo: add unit tests
> feat: physical qubits

- src/braket/analog_hamiltonian_simulator/rydberg/numpy_solver.py
- src/braket/analog_hamiltonian_simulator/rydberg/rydberg_simulator.py
- src/braket/analog_hamiltonian_simulator/rydberg/scipy_solver.py
Fixed a bug of the progress bar of ahs simulator. Now the progress bar is functional
unit tests
> fix: progress bar of ahs simulator

- src/braket/default_simulator/openqasm/program_context.py
> fix: Include `circuit` property in abstract context

- .coveragerc
- src/braket/default_simulator/openqasm/circuit.py
- src/braket/default_simulator/openqasm/interpreter.py
- src/braket/default_simulator/openqasm/parser/braket_pragmas.py
- src/braket/default_simulator/openqasm/program_context.py
- test/unit_tests/braket/default_simulator/openqasm/test_braket_gates.py
- test/unit_tests/braket/default_simulator/openqasm/test_circuit.py
- test/unit_tests/braket/default_simulator/openqasm/test_helpers.py
- test/unit_tests/braket/default_simulator/openqasm/test_interpreter.py
- test/unit_tests/braket/default_simulator/openqasm/test_program_context.py
> fix: Use op names for noise parsing

- .github/workflows/dependent-tests.yml
> infra: Remove SF plugin, add Python 3.11 to dependent tests

- setup.py
1.18.0 is required for Python 3.11 support
> Update schema dependency to 1.18.0

- src/braket/default_simulator/openqasm/interpreter.py
- src/braket/default_simulator/openqasm/program_context.py
> fix: Support for unbounded parametric circuits

- src/braket/default_simulator/openqasm/interpreter.py
> fix: indentation

- CHANGELOG.md
- src/braket/default_simulator/_version.py
- src/braket/default_simulator/openqasm/interpreter.py
- src/braket/default_simulator/openqasm/program_context.py
- test/unit_tests/braket/analog_hamiltonian_simulator/test_solvers.py
n/a
Merge latest changes from `main` to `mcm-sim` branch.
> infra: merge latest main to mcm-sim branch

- src/braket/default_simulator/openqasm/program_context.py
> doc: update type annotation for handle_parameter_value

- src/braket/default_simulator/openqasm/_helpers/arrays.py
- src/braket/default_simulator/openqasm/_helpers/casting.py
- src/braket/default_simulator/openqasm/_helpers/functions.py
- src/braket/default_simulator/openqasm/_helpers/quantum.py
- src/braket/default_simulator/openqasm/interpreter.py
- test/unit_tests/braket/default_simulator/openqasm/test_interpreter.py
Also added license headers to some files
https://github.com/aws/amazon-braket-sdk-python/issues/632
> fix: Support `angle` declarations

- .readthedocs.yml
https://blog.readthedocs.com/use-build-os-config/
tox
> infra: readthedocs integration change

- .github/dependabot.yml
> infra: Update dependabot to use the `infra:` prefix

- .github/pull_request_template.md
- CONTRIBUTING.md
- README.md
- doc/index.rst
- setup.py
- tox.ini
> doc: Replace aws org with amazon-braket

- src/braket/analog_hamiltonian_simulator/rydberg/numpy_solver.py
- src/braket/analog_hamiltonian_simulator/rydberg/rydberg_simulator_helpers.py
- src/braket/analog_hamiltonian_simulator/rydberg/rydberg_simulator_result_converter.py
- src/braket/analog_hamiltonian_simulator/rydberg/rydberg_simulator_unit_converter.py
- src/braket/analog_hamiltonian_simulator/rydberg/scipy_solver.py
- src/braket/analog_hamiltonian_simulator/rydberg/validators/atom_arrangement.py
- src/braket/analog_hamiltonian_simulator/rydberg/validators/field_validator_util.py
- src/braket/default_simulator/density_matrix_simulation.py
- src/braket/default_simulator/gate_operations.py
- src/braket/default_simulator/linalg_utils.py
- src/braket/default_simulator/noise_operations.py
- src/braket/default_simulator/observables.py
- src/braket/default_simulator/openqasm/_helpers/arrays.py
- src/braket/default_simulator/openqasm/_helpers/casting.py
- src/braket/default_simulator/openqasm/_helpers/functions.py
- src/braket/default_simulator/openqasm/_helpers/quantum.py
- src/braket/default_simulator/openqasm/circuit.py
- src/braket/default_simulator/openqasm/interpreter.py
- src/braket/default_simulator/openqasm/parser/braket_pragmas.py
- src/braket/default_simulator/openqasm/program_context.py
- src/braket/default_simulator/operation.py
- src/braket/default_simulator/operation_helpers.py
- src/braket/default_simulator/result_types.py
- src/braket/default_simulator/simulation.py
- src/braket/default_simulator/simulation_strategies/batch_operation_strategy.py
- src/braket/default_simulator/simulation_strategies/single_operation_strategy.py
- src/braket/default_simulator/simulator.py
- src/braket/default_simulator/state_vector_simulation.py
> Use builtins for type hints

- .github/workflows/check-format.yml
- .github/workflows/code-freeze.yml
- .github/workflows/twine-check.yml
- src/braket/analog_hamiltonian_simulator/rydberg/rydberg_simulator_helpers.py
- src/braket/analog_hamiltonian_simulator/rydberg/validators/times_series.py
Add code freeze workflow.
This PR will run the workflow, tested in BDK
> infra: add code freeze workflow

- src/braket/default_simulator/openqasm/interpreter.py
- src/braket/default_simulator/openqasm/program_context.py
- src/braket/default_simulator/simulator.py
- test/unit_tests/braket/default_simulator/openqasm/test_interpreter.py
- test/unit_tests/braket/default_simulator/test_state_vector_simulator.py
> feat: support symbols as qubit indices

- src/braket/default_simulator/openqasm/program_context.py
Adding `from __future__ import annotations` to avoid `TypeError: unsupported operand type(s) for |: 'type' and 'type'`
> add import of future annotations

- .github/workflows/check-format.yml
- .github/workflows/twine-check.yml
- tox.ini
> fix: add tox read only linters

- .github/workflows/publish-to-pypi.yml
> fix: add in setuptools for publishing to pypi

- src/braket/analog_hamiltonian_simulator/rydberg/validators/capabilities_constants.py
> fix: make the dimension a PositiveInt for typing

- setup.py
> change: update schema version to latest in setup.py

- src/braket/default_simulator/density_matrix_simulator.py
- src/braket/default_simulator/openqasm/_helpers/arrays.py
- src/braket/default_simulator/openqasm/circuit.py
- src/braket/default_simulator/openqasm/interpreter.py
- src/braket/default_simulator/openqasm/program_context.py
- src/braket/default_simulator/simulator.py
- src/braket/default_simulator/state_vector_simulator.py
- test/unit_tests/braket/default_simulator/openqasm/test_interpreter.py
- test/unit_tests/braket/default_simulator/test_density_matrix_simulator.py
- test/unit_tests/braket/default_simulator/test_state_vector_simulator.py
Add support for the OpenQASM `measure` instruction instead of just returning measurements for all qubits
- Add implementation of the `QuantumMeasurement` and `QuantumMeasurmementStatement` in `interpreter.py` to support the OpenQASM measure instruction instead of calculating all the qubit measurements
- Add measure qubit targets in the Circuit class
- Flip `requiresAllQubitsMeasurement` to False for the state vector and density matrix local simulators
- Update `simulator` to return a subset of measurements based on the measurement targets
- Add tests for the updated interpreter, simulator, and Circuit classes
tox
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about …
> feature: allow support for a subset of measurements

- .github/workflows/dependent-tests.yml
- setup.py
- src/braket/analog_hamiltonian_simulator/rydberg/rydberg_simulator.py
- src/braket/analog_hamiltonian_simulator/rydberg/validators/atom_arrangement.py
- src/braket/analog_hamiltonian_simulator/rydberg/validators/capabilities_constants.py
- src/braket/analog_hamiltonian_simulator/rydberg/validators/driving_field.py
- src/braket/analog_hamiltonian_simulator/rydberg/validators/hamiltonian.py
- src/braket/analog_hamiltonian_simulator/rydberg/validators/physical_field.py
- src/braket/analog_hamiltonian_simulator/rydberg/validators/program.py
- src/braket/analog_hamiltonian_simulator/rydberg/validators/shifting_field.py
- src/braket/analog_hamiltonian_simulator/rydberg/validators/times_series.py
- test/unit_tests/braket/analog_hamiltonian_simulator/test_validator/test_ir_validator.py
- test/unit_tests/braket/analog_hamiltonian_simulator/test_validator/validators/test_atom_arrangement.py
- test/unit_tests/braket/analog_hamiltonian_simulator/test_validator/validators/test_blockade_radius.py
- test/unit_tests/braket/analog_hamiltonian_simulator/test_validator/validators/test_driving_field.py
- test/unit_tests/braket/analog_hamiltonian_simulator/test_validator/validators/test_hamiltonian.py
- test/unit_tests/braket/analog_hamiltonian_simulator/test_validator/validators/test_physical_field.py
- test/unit_tests/braket/analog_hamiltonian_simulator/test_validator/validators/test_program.py
- test/unit_tests/braket/analog_hamiltonian_simulator/test_validator/validators/test_rydberg_coefficients.py
- test/unit_tests/braket/analog_hamiltonian_simulator/test_validator/validators/test_shifting_field.py
- test/unit_tests/braket/analog_hamiltonian_simulator/test_validator/validators/test_time_series.py
- tox.ini
fix: support pydantic 2.x
`tox` and ran against the latest branch of the schemas package to ensure compatibility.
> fix: support pydantic 2.x

- .github/workflows/dependent-tests.yml
> infra: restore dependent tests after the Pydantic migration

- src/braket/default_simulator/gate_operations.py
- src/braket/default_simulator/operation.py
> fix: Gates inherit `targets`

- test/unit_tests/braket/default_simulator/test_state_vector_simulator.py
> test: add basic tests for rx rotation expressions

- test/unit_tests/braket/analog_hamiltonian_simulator/test_get_coefs.py
> fix: use numpy for float comparison

- src/braket/default_simulator/density_matrix_simulation.py
- src/braket/default_simulator/linalg_utils.py
The multiply function already reshapes the matrix
> fix: remove redundant reshape

- src/braket/default_simulator/_version.py
Just ran the formatter so the linting isn't failing in the CI.
> infra: Failing linting CI test

- src/braket/analog_hamiltonian_simulator/rydberg/rydberg_simulator_helpers.py
*Description of changes:* fixed typo in title
*Testing done:* test state didn't change (one test fails which was the case before the changes)
> fix: typo detuing to detuning

- .gitignore
- setup.py
- src/braket/default_simulator/simulator.py
- src/braket/simulator/braket_simulator.py
- test/unit_tests/braket/default_simulator/test_density_matrix_simulator.py
- test/unit_tests/braket/default_simulator/test_state_vector_simulator.py
> feat: Program sets

- src/braket/default_simulator/density_matrix_simulation.py
- src/braket/default_simulator/linalg_utils.py
- src/braket/default_simulator/simulator.py
- test/unit_tests/braket/default_simulator/test_linalg_utils.py
> feat: generalize diagonal gate dispatch

- src/braket/default_simulator/density_matrix_simulation.py
- src/braket/default_simulator/gate_operations.py
- src/braket/default_simulator/linalg_utils.py
- src/braket/default_simulator/simulation_strategies/single_operation_strategy.py
- src/braket/default_simulator/simulator.py
- test/unit_tests/braket/default_simulator/test_linalg_utils.py
>  fix: add gate_types for dispatch and use np.kron for dm gate_ops

- src/braket/default_simulator/density_matrix_simulation.py
> fix: add gate_applications back to the dm sim

- src/braket/default_simulator/density_matrix_simulation.py
- src/braket/default_simulator/linalg_utils.py
> fix: Remove superoperator gate application

- src/braket/default_simulator/simulator.py
This operation can take a non trivial time with the new buffer functions
> fix: only apply basis instructions when needed
