.readthedocs.yml, doc/conf.py, doc/index.rst, doc/requirements.txt, setup.py, tox.ini
Fixed previously failing Read the Docs builds by:
1. Explicity adding `method` and `path` to .readthedocs.yml; this was causing builds to fail altogether
2. Using [sphinxcontrib-apidoc](https://github.com/sphinx-contrib/apidoc) instead autodoc directly (see readthedocs/readthedocs.org#1139). Defore, our `tox -e docs` command would run `aphinx-apidoc` then `sphinx-build`. However, Read the Docs only runs `sphinx-build`, so the module docs would never get generated.
[build_files.tar.gz](https://github.com/aws/amazon-braket-default-simulator-python/files/5077349/build_files.tar.gz)
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. …
=> documentation: Get Read the Docs working

src/braket/default_simulator/gate_operations.py, src/braket/default_simulator/result_types.py, src/braket/default_simulator/simulator.py, test/performance/test_performance.py, test/unit_tests/braket/default_simulator/test_gate_operations.py, test/unit_tests/braket/default_simulator/test_result_types.py, test/unit_tests/braket/default_simulator/test_simulator.py
* Allow simultaneous measurement of commuting observables, e.g. expectation(Pauli-X(0)), and variance(TensorProduct([PauliX(0), PauliY(1)]))
* Added unit test
=> change: Enable simultaneous measurement of observables with shared factors

src/braket/default_simulator/gate_operations.py, src/braket/default_simulator/result_types.py, src/braket/default_simulator/simulator.py, test/performance/test_performance.py, test/unit_tests/braket/default_simulator/test_gate_operations.py, test/unit_tests/braket/default_simulator/test_result_types.py, test/unit_tests/braket/default_simulator/test_simulator.py
This enables simultaneous measurement of qubit-wise commuting Pauli
words.
Also added validation to make sure Hermitian observables on more than 1
qubit that share a target qubit share all target qubits and in the same
order.
=> feature: Always accept identity observable factors

src/braket/default_simulator/observables.py, src/braket/default_simulator/operation.py, src/braket/default_simulator/operation_helpers.py, src/braket/default_simulator/simulation.py, src/braket/default_simulator/simulation_strategies/batch_operation_strategy.py, src/braket/default_simulator/simulation_strategies/single_operation_strategy.py, test/unit_tests/braket/default_simulator/test_gate_operations.py, test/unit_tests/braket/default_simulator/test_observables.py, test/unit_tests/braket/default_simulator/test_operation_helpers.py, test/unit_tests/braket/default_simulator/test_simulation.py
Currently, the simulator calculates the entire matrix of a tensor product observable before applying it, which is extremely inefficient. This change applies the diagonalizing gates of the factors individually.
=> change: Make tensor products more efficient

src/braket/default_simulator/result_types.py, src/braket/default_simulator/simulator.py, test/unit_tests/braket/default_simulator/test_density_matrix_simulation.py, test/unit_tests/braket/default_simulator/test_density_matrix_simulator.py, test/unit_tests/braket/default_simulator/test_result_types.py, test/unit_tests/braket/default_simulator/test_simulator.py, test/unit_tests/braket/default_simulator/test_state_vector_simulation.py, test/unit_tests/braket/default_simulator/test_state_vector_simulator.py
Allows arbitrary observables to be attached to a circuit, allowing, for example, the simultaneous calculation of all terms of a Hamiltonian.
This change only applies for `shots=0`, as result types are only defined for `shots=0` in this simulator. The `shots>0` case is handled entirely by the SDK, using samples generated by the simulator.
=> feature: Calculate arbitrary observables

src/braket/default_simulator/density_matrix_simulation.py, src/braket/default_simulator/density_matrix_simulator.py, src/braket/default_simulator/noise_operations.py, src/braket/default_simulator/observables.py, src/braket/default_simulator/result_types.py, src/braket/default_simulator/simulator.py, src/braket/default_simulator/state_vector_simulation.py, test/unit_tests/braket/default_simulator/test_density_matrix_simulation.py, test/unit_tests/braket/default_simulator/test_density_matrix_simulator.py, test/unit_tests/braket/default_simulator/test_noise_operations.py, test/unit_tests/braket/default_simulator/test_observables.py, test/unit_tests/braket/default_simulator/test_result_types.py, test/unit_tests/braket/default_simulator/test_state_vector_simulation.py, test/unit_tests/braket/default_simulator/test_state_vector_simulator.py
Adding support for two-qubit Pauli channel noise in the local simulator. 
Adding two-qubit Pauli channel to existing tests. 
=> feature: adding two qubit Pauli channels

src/braket/default_simulator/openqasm/interpreter.py, src/braket/default_simulator/openqasm/program_context.py, test/unit_tests/braket/default_simulator/openqasm/test_interpreter.py, test/unit_tests/braket/default_simulator/test_density_matrix_simulator.py, test/unit_tests/braket/default_simulator/test_state_vector_simulator.py
Log a warning when user is using OpenQASM features that are only supported in the local sim
unit testing to make sure warnings are displayed when using advanced features and NOT DISPLAYED when not.
=> feature: warning when using advanced language features

src/braket/default_simulator/openqasm/interpreter.py, test/unit_tests/braket/default_simulator/openqasm/test_interpreter.py
Was raising a warning when encountering binary expressions in the builtin gate definitions-- too sensitive, added a clause to stop incorrect warnings from going off.
Also no warning for phase instruction, since it's already listed in device properties as an operation. And we run into the same issue with being referenced in the builtin gates.
Added a test
=> fix: no warning for binary expression in gate def

src/braket/analog_hamiltonian_simulator/rydberg/rydberg_simulator_result_converter.py, test/unit_tests/braket/analog_hamiltonian_simulator/test_convert_result.py
When some sites were left empty in the AHS program, the preSequence and postSequence in the results becomes inconsistent: they have different lengths, and postSequence only contains the results from non-empty sites.
This is due to a bug in `convert_result`.
Implementation of `convert_result` is changed. Now it creates the postSequence list starting from an all-zero list of length of the preSequence, and fills in the measurement results for non-empty sites to their appropriate locations in the list.
Added test to highlight the bug to `test_convert_result.py`
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! …
=> bugfix: Feature/neutral atom simulator empty site bug

test/unit_tests/braket/default_simulator/openqasm/test_interpreter.py
we want "\." in the string, meaning we need to escape the backslash not the period "\\."
this change fixes a warning about invalid escape sequence "\."
unit tests
=> fix: regex escape char in unit test

setup.cfg, setup.py
Currently, the project unnecessarily pins `pydantic`'s version to 1.9.0. This strict constraint can be problematic itself when using it as a dependency in other projects. In addition, since this project is a dependency for the `amazon-braket-sdk`, this constraint will also apply to any package that wants to integrate with Amazon Braket through the SDK. Relaxing the version constraint to any version compatible with 1.9 can guarantee that there won't be a breaking change while offering the necessary flexibility.
In addition, I fixed flake8's configuration to fit the new version 6.0.0; otherwise, it will fail.
All tests pass with `pydantic`'s latest version 1.10.2.
_Put an `x` in the boxes that apply. You can also fill these …
=> Relax pydantic version constraint

src/braket/default_simulator/openqasm/interpreter.py, test/unit_tests/braket/default_simulator/openqasm/test_interpreter.py
Now that the service supports binary expressions, this should no longer throw the "advanced language features" warning
Unit test and manual notebook example test
=> fix: remove warning for binary expressions

setup.py
Remove sim endpoints for BraketOpenQASM simulators (point to non-existent classes)
unit tests and manually confirmed these names don't work today
=> fix: remove oq3 named sims

src/braket/analog_hamiltonian_simulator/rydberg/rydberg_simulator.py
[One of the recent change](https://github.com/aws/amazon-braket-default-simulator-python/blob/c71f04f792a5e0f25ef8126eae4b08f3eaa2444a/src/braket/analog_hamiltonian_simulator/rydberg/rydberg_simulator.py#L126) causes a notebook to take long to complete. After a more careful benchmark, we decide to roll back this change.
Change the boundary from 32 back to 1000
Yes
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …
=> fix: Revert threshold to switch AHS solvers

src/braket/default_simulator/linalg_utils.py, src/braket/default_simulator/operation.py, src/braket/default_simulator/simulation_strategies/single_operation_strategy.py, test/unit_tests/braket/default_simulator/openqasm/test_interpreter.py
Instead of building a controlled unitary, which grows exponentially wrt to the number of control qubits, mask the state to only update the halves that fall under the control condition.
Nits:
- removed "public" method `controlled_unitary` from linalg_utils, since it's no longer used; can keep this around if this would be considered breaking
- Currently the interpreter tracks the ctrl/negctrl enum as 0/1 respectively, which is flipped from the control state. Have kept this field as private to not highlight this, can shift this approach around as preferred.
Existing unit testing
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. …
=> feat: optimize performance for simulating control modifiers

src/braket/analog_hamiltonian_simulator/rydberg/rydberg_simulator_helpers.py, test/.benchmarks/Darwin-CPython-3.9-64bit/0001_e09fe39b7d0b877e70e15e6d4aa27c25eb54654b_20230415_181107.json, test/.benchmarks/Darwin-CPython-3.9-64bit/0002_e09fe39b7d0b877e70e15e6d4aa27c25eb54654b_20230415_181551.json, test/unit_tests/braket/analog_hamiltonian_simulator/test_get_dicts_ops.py
N/A
changed the implementation of `get_rabi_dict` based on the proposal in PR #152. Intead of using a new configuration the dictionary is created when the rabi term is constructed since this only happens a few times. 
unit tests are passing. new unit tests required for full code coverage which is added. 
=> New implementation for helper `_get_rabi_dict` in rydberg AHS. 

CODEOWNERS
=> infra: update team for CODEOWNERS

src/braket/default_simulator/openqasm/program_context.py, src/braket/default_simulator/simulation_strategies/single_operation_strategy.py
Align internal mapping of ctrl/negctrl with state being controlled on
regression testing
=> fix: flip internal mapping for ctrl/negctrl

src/braket/analog_hamiltonian_simulator/rydberg/rydberg_simulator_helpers.py, test/unit_tests/braket/analog_hamiltonian_simulator/test_rydberg_simulator.py
We introduced a bug in [the PR 180](https://github.com/aws/amazon-braket-default-simulator-python/pull/180) because driving field (and shifting field) is a list of list. The list is of length 1 because there is only one driving field now. This PR is a more robust fix for the issues https://github.com/aws/amazon-braket-default-simulator-python/issues/168 and https://github.com/aws/amazon-braket-default-simulator-python/issues/176 because it also considers the case where there is only shifting fields, but no driving field.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we …
=> fix: fix index time clamping bug

src/braket/default_simulator/openqasm/interpreter.py, src/braket/default_simulator/simulator.py, src/braket/simulator/braket_simulator.py
This exposes an easy-to-use `parse_program` method to be used in conjunction a custom program contexts to handle the instantiation of the `Interpreter` and calling its `run` method.
Also reversed the dependency of `run` on `build_circuit`.
=> feat: Create OpenQASMSimulator class

src/braket/default_simulator/openqasm/native_interpreter.py, test/unit_tests/braket/default_simulator/openqasm/test_native_interpreter.py
visit qubit node of reset
Enabling using identifier as qubit index for reset.
```
OPENQASM 3.0;
qubit[2] __qubits__;
array[int[32], 2] __arr_0__ = {0, 1};
for int q in __arr_0__ {
reset __qubits__[q];
}
```
tox
=> fix: visit reset qubit node

doc/conf.py, setup.cfg, setup.py
This relaxes the constraints for what Pydantic version is used. This imports the schemas package which already dictates that for Braket packages. If this relationship is decoupled, then would make sense to add back.
Ran unit tests and linters
=> infra: remove pydantic constraints

src/braket/analog_hamiltonian_simulator/rydberg/numpy_solver.py, src/braket/analog_hamiltonian_simulator/rydberg/rydberg_simulator_helpers.py, src/braket/analog_hamiltonian_simulator/rydberg/scipy_solver.py
=> fix: typing issue for apply_hamiltonian

setup.py
Pydantic version conflicts will be incompatible for later versions of the schemas package. For allowing installs of this package to succeed, the schemas version is constrained.
=> fix: constrain the schemas for upgrading Pydantic

src/braket/analog_hamiltonian_simulator/rydberg/rydberg_simulator_helpers.py, src/braket/default_simulator/_version.py, test/unit_tests/braket/analog_hamiltonian_simulator/test_solvers.py
There is a bug in the AHS local simulator when it is used to simulate AHS program with local detuning with patterns where an empty site is specified before another filled site. This bug originates from [this line](https://github.com/amazon-braket/amazon-braket-default-simulator-python/blob/420aeaf5e2d8366cea7ac7a3d4cf0214a8fc3aa3/src/braket/analog_hamiltonian_simulator/rydberg/rydberg_simulator_helpers.py#L76) and  [this line](https://github.com/amazon-braket/amazon-braket-default-simulator-python/blob/420aeaf5e2d8366cea7ac7a3d4cf0214a8fc3aa3/src/braket/analog_hamiltonian_simulator/rydberg/rydberg_simulator_helpers.py#L260) where the former only indexes the filled sites but the latter loop through all the empty and filled sites. 
Hence, there will be a bug if and …
=> fix: Fix a bug in the AHS local simulator when using local detuning with certain pattern with empty sites 

src/braket/default_simulator/_version.py, src/braket/default_simulator/openqasm/program_context.py, test/unit_tests/braket/default_simulator/openqasm/test_interpreter.py
`GPhase` applies to no qubits rather than all qubits when no targets are supplied.
=> fix: Make `GPhase` more efficient

src/braket/analog_hamiltonian_simulator/rydberg/constants.py, src/braket/analog_hamiltonian_simulator/rydberg/validators/capabilities_constants.py, src/braket/analog_hamiltonian_simulator/rydberg/validators/field_validator_util.py, src/braket/analog_hamiltonian_simulator/rydberg/validators/program.py, test/unit_tests/braket/analog_hamiltonian_simulator/test_validator/validators/test_program.py
=> feat: local detuning validation for ahs

src/braket/default_simulator/openqasm/_helpers/functions.py, src/braket/default_simulator/openqasm/interpreter.py, test/unit_tests/braket/default_simulator/openqasm/test_interpreter.py
*Issue:* #240
Fixes bug [#240] by casting node.size into IntegerLiteral.
Building a circuit from a quasi string raises an `AttributeError` exception in case the qubit register is specified as a string literal.
A unit-test is added that checks that the `AttributeError` is not raised anymore.
=> fix: cast node.size to IntegerLiteral for qubit register size

src/braket/default_simulator/openqasm/_helpers/casting.py, test/unit_tests/braket/default_simulator/openqasm/test_interpreter.py
Prior to this change, signed integer casting worked based on sign+magnitude. This change will use two's complement.
* https://openqasm.com/language/types.html#casting-from-int-uint
* https://openqasm.com/language/types.html#casting-from-bit
=> fix: fix signed integer casting

src/braket/analog_hamiltonian_simulator/rydberg/rydberg_simulator_helpers.py
`csr_matrix.H` has been [removed](https://docs.scipy.org/doc/scipy/release/1.14.0-notes.html#expired-deprecations) in SciPy 1.14.0.
=> fix: Use csr_matrix.getH() instead of H

src/braket/default_simulator/openqasm/circuit.py, src/braket/default_simulator/simulator.py, test/resources/discontiguous.qasm, test/resources/noncontiguous_jaqcd.json, test/resources/noncontiguous_physical.qasm, test/resources/noncontiguous_virtual.qasm, test/unit_tests/braket/default_simulator/test_density_matrix_simulator.py, test/unit_tests/braket/default_simulator/test_state_vector_simulator.py
=> fix: Include measured in noncontiguous qubit map

src/braket/default_simulator/simulator.py, test/unit_tests/braket/default_simulator/test_state_vector_simulator.py
=> change: Ignore `qubit_count` parameter for JAQCD

src/braket/default_simulator/simulator.py, src/braket/simulator/braket_simulator.py, test/unit_tests/braket/default_simulator/test_density_matrix_simulator.py, test/unit_tests/braket/default_simulator/test_state_vector_simulator.py
Introduces `run_multiple` method to `BraketSimulator` to allow backends to leverage their own batching implementations. Will next publish SDK PR to make use of this interface.
=> feat: Introduce `run_multiple` method

setup.py
Updating pytest version to get past security vulnerability.
https://github.com/advisories/GHSA-w596-4wvx-j9j6
All tests passed locally when running the *Run the Unit Tests* commands in `Contributing.md`.
=> fix: update pytest version to fix security vuln

src/braket/default_simulator/simulator.py
https://numpy.org/doc/2.1/reference/generated/numpy.ndarray.tostring.html - tostring is gone, using `tobytes` instead
=> fix: change numpy tostring to tobytes

.github/workflows/python-package.yml, setup.py, tox.ini
This fixes the test errors for Windows with Python 3.13; before this fix, pytest would break with the error
```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "C:\Users\cody\anaconda3\Lib\getpass.py", line 172, in getuser
INTERNALERROR>     import pwd
INTERNALERROR> ModuleNotFoundError: No module named 'pwd'
INTERNALERROR>
INTERNALERROR> The above exception was the direct cause of the following exception:
INTERNALERROR>
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "C:\Users\cody\GitHub\amazon-braket-default-simulator-python\.tox\unit-tests\Lib\site-packages\_pytest\main.py", line 269, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^ …
```
=> fix: Pass username to testenv

test/unit_tests/braket/default_simulator/openqasm/test_interpreter.py
*Description of changes:* Multiple tests are added to make sure that the local simulator can interpret `barrier` instructions in an openqasm file.
*Testing done:* tox
=> feat: Add tests to make sure the simulator can handle `barrier` instructions
